# Generated by Django 3.2.16 on 2023-08-23 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_repo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to=file_repo.models.user_directory_path)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='file type from frontend')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_fr', models.CharField(max_length=255, null=True, unique=True)),
                ('name_de', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('max_size_in_byte', models.IntegerField(default=209715200)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('same_meta_for_each_file', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('INIT', 'INIT'), ('FILE_UPLOADED', 'FILE_UPLOADED'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR'), ('ABORTED', 'ABORTED')], default='INIT', max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatorGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='file_repo.pipeline')),
                ('validator_groups', models.ManyToManyField(to='file_repo.ValidatorGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UploadValidation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, choices=[('NOT_VALIDATED', 'not_validated'), ('VALIDATED_OK', 'validated_ok'), ('VALIDATED_NOK', 'validated_nok')], default='NOT_VALIDATED', max_length=255, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_repo.validatorgroup')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='file_repo.upload')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_validations', to='file_repo.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=255)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='file_repo.upload')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='file_repo.fileupload')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataFormsField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('label_fr', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('label_de', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('key', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('TEXT', 'text'), ('CHECKBOX', 'checkbox'), ('NUMBER', 'number'), ('DATE', 'date'), ('TEXT_AREA', 'text_area'), ('SELECT', 'select'), ('TIME', 'time'), ('DURATION', 'duration')], default='TEXT', max_length=255, null=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='file_repo.pipeline')),
                ('scope', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'ordering': ['scope', 'order'],
                'unique_together': {('id', 'key')},
            },
        ),
        migrations.AddField(
            model_name='fileupload',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_repo.upload'),
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pipeline', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_repo.pipeline')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedFileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mime', models.CharField(max_length=255)),
                ('pipeline', models.ManyToManyField(blank=True, related_name='mimes', to='file_repo.Pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('value_fr', models.CharField(max_length=255, null=True)),
                ('value_de', models.CharField(max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('dflt', models.BooleanField(default=False)),
                ('form_field', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='file_repo.metadataformsfield')),
            ],
            options={
                'unique_together': {('id', 'key')},
            },
        ),
    ]
